list_id = "list_1770986738095379145"

[metadata]
name = "ManyMods"

[metadata.game_version]
name = "1.21.11"
channel = "release"

[type_config.mod]
download_dir = "/home/marcus/.minecraft/mods"

[type_config.mod.loader]
id = "fabric"
name = "Fabric"

[[projects]]
project_id = "JygyCSA4"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095392465Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Item Scroller"
description = "A client mod that adds many shortcuts to move items easier and craft faster in inventory screens"
author = "masa"

[[projects]]
project_id = "bEpr0Arc"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095411273Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Litematica"
description = "A client-side schematic mod with extra features for creative mode work"
author = "masa"

[[projects]]
project_id = "UMxybHE8"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095418943Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "MiniHUD"
description = 'A "mini F3" HUD mod, also with various overlays like light level, spawn chunks, slime chunks etc.'
author = "masa"

[[projects]]
project_id = "zV5r3pPn"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095428062Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "3D Skin Layers"
description = "Render the player skin layer in 3d!"
author = "tr7zw"

[[projects]]
project_id = "EsAfCjCV"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095432542Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "AppleSkin"
description = "Food/hunger-related HUD improvements"
author = "squeek502"

[[projects]]
project_id = "8shC1gFX"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095438362Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "BetterF3"
description = "BetterF3 is a mod that replaces Minecraft's original debug HUD with a highly customizable, more human-readable HUD."
author = "TreyRuffy"

[[projects]]
project_id = "M08ruV16"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095445011Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Bobby"
description = "Allows for render distances greater than the server's view-distance"
author = "Johni0702"

[[projects]]
project_id = "VSNURh3q"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095448511Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Concurrent Chunk Management Engine (Fabric)"
description = "A Fabric mod designed to improve the chunk performance of Minecraft."
author = "ishland"

[[projects]]
project_id = "rrwQMaWQ"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095459260Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Camera Utils"
description = "Helpful camera utilities"
author = "henkelmax"

[[projects]]
project_id = "m0oRwcZx"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095487948Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Camera Overhaul"
description = "A mod that makes gameplay & movement more satisfying through the use of various camera rotations, and more!"
author = "Mirsario"

[[projects]]
project_id = "Wb5oqrBJ"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095496278Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Chat Heads"
description = "See who you're chatting with!"
author = "dzwdz"

[[projects]]
project_id = "9s6osm5g"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095500788Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Cloth Config API"
description = "Configuration Library for Minecraft Mods"
author = "shedaniel"

[[projects]]
project_id = "1IjD5062"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095506297Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Continuity"
description = "A Minecraft mod that allows for efficient connected textures"
author = "Pepper_Bell"

[[projects]]
project_id = "ZfQ3kTvR"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095511157Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "DashLoader"
description = "Launch at the speed of light."
author = "alphaqu"

[[projects]]
project_id = "HdwRs3kc"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095515457Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Disable Custom Worlds Advice"
description = "Minecraft asking you if you want to load a custom world is annoying. Let's fix it!"
author = "naritanara"

[[projects]]
project_id = "uCdwusMi"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095521966Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Distant Horizons"
description = "See farther without turning your game into a slide show"
author = "jeseibel"

[[projects]]
project_id = "ZcR9weSm"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095532155Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Dynamic Crosshair"
description = "A mod that hides or changes the crosshair dependent on context"
author = "Crendgrim"

[[projects]]
project_id = "rUgZvGzi"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095564343Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Eating Animation"
description = "A mod that adds sprite animations for edible and drinkable items."
author = "theoness1"

[[projects]]
project_id = "4I1XuqiY"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095569463Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "[EMF] Entity Model Features"
description = "EMF is an, OptiFine format, Custom Entity Model replacement mod available for Fabric and Forge."
author = "Traben"

[[projects]]
project_id = "NNAgCjsB"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095574593Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Entity Culling"
description = "Using async path-tracing to hide Block-/Entities that are not visible"
author = "tr7zw"

[[projects]]
project_id = "BVzZfTc1"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095580212Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "[ETF] Entity Texture Features"
description = "Emissive, Random & Custom texture support for entities in resourcepacks just like Optifine but for Fabric"
author = "Traben"

[[projects]]
project_id = "P7dR8mSH"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095585562Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Fabric API"
description = "Lightweight and modular API providing common hooks and intercompatibility measures utilized by mods using the Fabric toolchain."
author = "modmuss50"

[[projects]]
project_id = "Ha28R6CL"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095601731Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Fabric Language Kotlin"
description = "This is a mod that enables usage of the Kotlin programming language for Fabric mods."
author = "modmuss50"

[[projects]]
project_id = "WhbRG4iK"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095620240Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Falling Leaves"
description = "Adds a neat little particle effect to leaf blocks"
author = "Fourmisain"

[[projects]]
project_id = "uXXizFIs"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095629659Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "FerriteCore"
description = "Memory usage optimizations"
author = "malte0811"

[[projects]]
project_id = "H5XMjpHi"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095637709Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "First-person Model"
description = "Enables the third-person Model in first-person"
author = "tr7zw"

[[projects]]
project_id = "ohNO6lps"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095647558Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Forge Config API Port"
description = "NeoForge's & Forge's config systems provided to other modding ecosystems. Designed for a multiloader architecture."
author = "Fuzs"

[[projects]]
project_id = "RnxjxXAI"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095655057Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Horse Statistics"
description = "A lightweight mod that shows the stats of horses (health, jump height, speed, owner and slots for Llamas). Client-sided mod, you don't need it for your server!"
author = "lilgallon"

[[projects]]
project_id = "5ZwdcRci"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095661377Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "ImmediatelyFast"
description = "Speed up immediate mode rendering in Minecraft"
author = "RaphiMC"

[[projects]]
project_id = "VD1aynYU"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095667617Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Inventory Tabs"
description = "Allows swapping to other in-world screens (blocks, entities, etc) via tabs. A fourth-generation rewrite of CakeWhip's InventoryTabs."
author = "sisby-folk"

[[projects]]
project_id = "YL57xq9U"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095673546Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Iris Shaders"
description = "A modern shader pack loader for Minecraft intended to be compatible with existing OptiFine shader packs"
author = "coderbot"

[[projects]]
project_id = "RPOSBQgq"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095680536Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "ItemSwapper"
description = "Inventory update concept for hotswapping items."
author = "tr7zw"

[[projects]]
project_id = "fQEb0iXm"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095686725Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Krypton"
description = "A mod to optimize the Minecraft networking stack"
author = "astei"

[[projects]]
project_id = "yBW8D80W"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095703124Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "LambDynamicLights - Dynamic Lights"
description = "Adds dynamic lights to Minecraft as the most feature-complete and optimized dynamic lighting mod."
author = "LambdAurora"

[[projects]]
project_id = "onSQdWhM"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095710844Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "libIPN"
description = "Inventory Profiles Next GUI/Config library"
author = "blackd"

[[projects]]
project_id = "cpbKeMPQ"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095719773Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Librarian Trade Finder"
description = "A fabric mod that helps you find the enchantments you need from a Librarian Villager."
author = "greeenman999"

[[projects]]
project_id = "gvQqBUqZ"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095728683Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Lithium"
description = "No-compromises game logic optimization mod. Well suited for clients and servers of all kinds. Now available for Fabric and NeoForge!"
author = "jellysquid3"

[[projects]]
project_id = "QdG47OkI"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095737932Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Model Gap Fix"
description = "Fixes gaps in Block Models and Item Models"
author = "MehVahdJukaar"

[[projects]]
project_id = "nmDcB62a"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095746122Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "ModernFix"
description = "All-in-one mod that improves performance, reduces memory usage, and fixes many bugs. Compatible with all your favorite performance mods!"
author = "embeddedt"

[[projects]]
project_id = "mOgUt4GM"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095755831Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Mod Menu"
description = "Adds a mod menu to view the list of mods you have installed."
author = "Prospector"

[[projects]]
project_id = "51shyZVL"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095768720Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "More Culling"
description = "A mod that changes how multiple types of culling are handled in order to improve performance"
author = "FX"

[[projects]]
project_id = "qQyHxfxd"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095776620Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "No Chat Reports"
description = "Makes chat unreportable (where possible)"
author = "Aizistral"

[[projects]]
project_id = "MPCX6s5C"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095787479Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Not Enough Animations"
description = "Bringing first-person animations to the third-person"
author = "tr7zw"

[[projects]]
project_id = "yM94ont6"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095799248Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Not Enough Crashes"
description = "When crashing, you can go back to the title screen and keep playing, without needing to restart, alongside other things to make crashes more pleasant."
author = "natanfudge"

[[projects]]
project_id = "ZX66K16c"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095814767Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Pick Up Notifier"
description = "Be notified about all the things you've just collected."
author = "Fuzs"

[[projects]]
project_id = "rcTfTZr3"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095824986Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Presence Footsteps"
description = "..An Overly complicated Sound Mod..."
author = "Sollace"

[[projects]]
project_id = "QAGBst4M"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095839255Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Puzzles Lib"
description = "Why it's called Puzzles, you ask? That's the puzzle!"
author = "Fuzs"

[[projects]]
project_id = "nCQRBEiR"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095860014Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Raised"
description = "Take control of the position of your GUI and fix the broken hotbar selection texture!"
author = "yurisuika"

[[projects]]
project_id = "Bh37bMuy"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095905351Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Reese's Sodium Options"
description = "Alternative Options Menu for Sodium"
author = "FlashyReese"

[[projects]]
project_id = "ZP7xHXtw"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095918210Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Remove Reloading Screen"
description = "Makes resource packs load in the background, allowing you to do other things while waiting!"
author = "dima_dencep"

[[projects]]
project_id = "9eGKb6K1"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095930930Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Simple Voice Chat"
description = "A working voice chat in Minecraft!"
author = "henkelmax"

[[projects]]
project_id = "AANobbMI"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095956568Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Sodium"
description = "The fastest and most compatible rendering optimization mod for Minecraft. Now available for both NeoForge and Fabric!"
author = "jellysquid3"

[[projects]]
project_id = "PtjYWJkn"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095968887Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Sodium Extra"
description = "A Sodium addon that adds features that shouldn't be in Sodium."
author = "FlashyReese"

[[projects]]
project_id = "qyVF9oeo"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095981476Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Sound Physics Remastered"
description = "A Minecraft mod that provides realistic sound attenuation, reverberation, and absorption through blocks."
author = "henkelmax"

[[projects]]
project_id = "l6YH9Als"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.095994165Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "spark"
description = "spark is a performance profiler for Minecraft clients, servers and proxies."
author = "lucko"

[[projects]]
project_id = "x02cBj9Y"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096007445Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Status Effect Bars"
description = "Adds customizable bars to the status effects overlay to show the remaining duration of effects."
author = "A5b84"

[[projects]]
project_id = "GBeCx05I"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096021364Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "TweakerMore"
description = "A collection of client-side tweak kits to enhance your Minecraft game experience. Tweak Minecraft and beyond!"
author = "fallen-breath"

[[projects]]
project_id = "1u6JkXh5"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096033973Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "WorldEdit"
description = """
A Minecraft Map Editor... that runs in-game!
With selections, schematics, copy and paste, brushes, and scripting.
Use it in creative, or use it temporarily in survival."""
author = "onM88Ia7"

[[projects]]
project_id = "NSLJJooQ"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096046952Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "WorldEdit CUI"
description = "WorldEdit CUI is a graphical user interface for WorldEdit, designed to assist in using WorldEdit and prevent accidental errors."
author = "7qQORuZ5"

[[projects]]
project_id = "1bokaNcj"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096060151Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Xaero's Minimap"
description = "Displays a map of the nearby world terrain, players, mobs, entities in the corner of your screen. Lets you create waypoints which help you find the locations you've marked."
author = "thexaero"

[[projects]]
project_id = "NcUtCpym"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096073860Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Xaero's World Map"
description = "Adds a full screen world map which shows you what you have explored in the world. Works great together with Xaero's Minimap."
author = "thexaero"

[[projects]]
project_id = "1eAoo2KR"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096087479Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "YetAnotherConfigLib (YACL)"
description = "A builder-based configuration library for Minecraft!"
author = "isxander"

[[projects]]
project_id = "Dk6su9JN"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096101738Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Cut Through"
description = "Cleanly swing through transparent blocks like tall grass to hit mobs without breaking said block."
author = "Fuzs"

[[projects]]
project_id = "BdKIyOLe"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096115098Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Boat Item View"
description = "See your held items when in a moving boat!"
author = "50ap5ud5"

[[projects]]
project_id = "yXAvIk0x"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096128987Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Scribble"
description = "Expertly edit your books with rich formatting options, page utilities and more!"
author = "chrrs"

[[projects]]
project_id = "L4pt5egz"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096162844Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Locator Heads"
description = "Show player heads on the locator bar and other usefull settings."
author = "Haage"

[[projects]]
project_id = "Si9Uim4y"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096176244Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Detail Armor Bar Reconstructed"
description = "More details about armor in the armor bar!"
author = "Coredex"

[[projects]]
project_id = "1E2sq1cp"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096191912Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "VTDownloader"
description = "Pick and download Vanilla Tweaks resource packs directly from your Minecraft client!"
author = "IotaBread"

[[projects]]
project_id = "nvQzSEkH"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096206212Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Jade 🔍"
description = "Shows information about what you are looking at. (Hwyla/Waila fork for Minecraft 1.16+)"
author = "Snownee"

[[projects]]
project_id = "uLbm7CG6"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096223680Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Language Reload"
description = "Reduces load times and adds fallbacks for languages"
author = "Jerozgen"

[[projects]]
project_id = "8qkXwOnk"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096239559Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "More Chat History"
description = "Increases the maximum length of chat history."
author = "JackFred"

[[projects]]
project_id = "x1hIzbuY"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096264788Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "FastQuit"
description = "Lets you return to the Title Screen early while your world is still saving in the background!"
author = "contaria"

[[projects]]
project_id = "PLAGcSFJ"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096280207Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Particle Effects"
description = "Visual Mod which adds unique textured particles for every effect in vanilla Minecraft!"
author = "cmRwIvyL"

[[projects]]
project_id = "pMBcsVIg"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096294846Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Locator Lodestones"
description = "Adds Lodestones to the Player Locator Bar"
author = "Pneumono_"

[[projects]]
project_id = "kqJFAPU9"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096313905Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Better Mount HUD"
description = "Improves the ingame HUD while riding a mount"
author = "Lortseam"

[[projects]]
project_id = "5srFLIaK"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096329973Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Better Clouds"
description = "Beautiful clouds in touch with the vanilla style"
author = "qendolin"

[[projects]]
project_id = "UR0ocuEt"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096343333Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "NBT Autocomplete"
description = "Adds suggestions for NBT tags in commands"
author = "mt1006"

[[projects]]
project_id = "8iQcgjQ2"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096353582Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Better Command Block UI"
description = "Provides a more usable Command Block UI"
author = "Tec"

[[projects]]
project_id = "hYykXjDp"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096363481Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Fzzy Config"
description = "Config API with automatic GUIs, powerful validation options, server-client sync, and more!"
author = "fzzyhmstrs"

[[projects]]
project_id = "4q8UOK1d"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096373831Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Subtle Effects"
description = "Adding many new subtle details through particles and a few sounds"
author = "MincraftEinstein"

[[projects]]
project_id = "rI0hvYcd"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096382590Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Visuality"
description = "Little visual improvements by adding a bunch of new particles."
author = "PinkGoosik"

[[projects]]
project_id = "lO3s8hjs"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096392479Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Bridging Mod"
description = "Reacharound Placement / Bedrock Bridging for Fabric, Forge & Quilt with a few extra tweaks"
author = "CG360"

[[projects]]
project_id = "JIUF2Wb5"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096402749Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Effect Timer Plus"
description = "Adds a potency and time indicator overlay to status effect icons."
author = "xcYFxFyi"

[[projects]]
project_id = "hTGmExq6"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096413328Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "GUI Followers"
description = "🐺 Shows a list in the GUI/HUD of all tamed non-sitting followers around."
author = "Serilum"

[[projects]]
project_id = "e0M1UDsY"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096424057Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Collective"
description = "🎓 Collective is a shared library with common code for all of Serilum's mods."
author = "Serilum"

[[projects]]
project_id = "kKwy3HU9"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096433917Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Better Beds"
description = "Changes the renderer of the bed to use json models instead of a block entity renderer! "
author = "Motschen"

[[projects]]
project_id = "RLzHAoZe"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096444066Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Resourcify"
description = "In-game resource pack, data pack and shader browser and updater."
author = "DeDiamondPro"

[[projects]]
project_id = "REfW2AEX"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096456215Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "InvMove"
description = "Forge/Fabric/Quilt mod that adds the ability to walk around while in inventories"
author = "PieKing1215"

[[projects]]
project_id = "iDyqnQLT"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096467834Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Cool Rain"
description = "Creates ambient sounds for certain blocks during rain"
author = "Jaiz"

[[projects]]
project_id = "T6oqPfxF"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096477534Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Xaero Zoomout"
description = "Reduces the minimum zoom of Xaero's World Map from 0.0625x to 0.0025x, so you can see everything!"
author = "NotRyken"

[[projects]]
project_id = "rIC2XJV4"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096487583Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "ViaFabricPlus"
description = "Minecraft Fabric mod which allows you to join EVERY Minecraft server version (Classic, Alpha, Beta, Release, April Fools, Bedrock)"
author = "florianreuth"

[[projects]]
project_id = "XoHTb2Ap"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096498223Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "CalcMod"
description = "A calculator in your chat with shortcuts designed for Minecraft"
author = "js802025"

[[projects]]
project_id = "g1yXisD2"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096510072Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "GUI Clock"
description = "⏰ Shows the time/days played in the GUI/HUD with a clock in the inventory."
author = "Serilum"

[[projects]]
project_id = "G4udXdNu"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096522041Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "Bedrock Miner"
description = "A fabric client mod to mine bedrock!"
author = "bunnyi116"

[[projects]]
project_id = "vqnOCHgM"
resource_type = "mod"
is_manual = true
added_at = "2026-02-13T12:45:38.096533520Z"

[projects.settings]
archived = false
compat_overruled = false
dependents = []

[projects.cache]
name = "BoatView360"
description = "Removes the 210° rotation limit for boat passengers, allowing full 360° camera rotation."
author = "AsOne2020"

[config]
version = 1
created_at = "2026-02-13T12:45:38.095382305Z"
show_archived = false
show_unknown_mods = false

[config.sort_settings]
sort_mode = "Name"
order_mode = "Ascending"
filter_mode = "All"
